# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '3F Movie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 3F Movie
  pod 'Kingfisher'
  pod 'SKPhotoBrowser'
  pod 'YoutubePlayer-in-WKWebView'
  pod 'FaveButton'
end
